document.writeln("<script language=\"javascript\">");
document.writeln("	function checksjiansuo(){");
document.writeln("	if(document.formjiansuo.gjz.value==\"\"){");
document.writeln("		alert(\"请输入查询关键字\");");
document.writeln("		document.formjiansuo.gjz.focus();");
document.writeln("		return false;");
document.writeln("	}");
document.writeln("	}");
document.writeln("<\/script>");
document.writeln("<iframe height=0 width=0 src=\"\" id=\"capitalframe\"><\/iframe>");
document.writeln("<script language=\"javascript\">");
document.writeln("function GetCapital(capitalid){");
document.writeln("	document.frames[\"capitalframe\"].location.replace(\"\/fs_inc\/getcapital.asp?capitalid=\"+capitalid);");
document.writeln("	if (document.form.sheng.value==\"\"){");
document.writeln("		document.form.city.value=\"\";");
document.writeln("	}");
document.writeln("}");
document.writeln("<\/script>");
document.writeln("<Table border=\"0\" width=\"210\" cellpadding=\"2\" cellspacing=\"0\" class=\"lan1\">");
document.writeln("	<tr><td height=\"10\"></td></tr>");
document.writeln("<form action=\"/morefiles.asp\" method=\"post\" name=\"formjiansuo\">");
document.writeln("	<tr>");
document.writeln("		<Td width=\"80\" align=\"right\">信息类型:<\/Td>");
document.writeln("		<td width=\"130\">");
document.writeln("			<SELECT name=\"xxlb\" style=\"width:130px;height:18px;\">");
document.writeln("			<OPTION value=\"\" selected>类 型 不 限<\/OPTION>");
document.writeln("			<OPTION value=\"0\">场地转让<\/OPTION>");
document.writeln("			<OPTION value=\"1\">项目转让<\/OPTION>");
document.writeln("			<OPTION value=\"2\">执照转让<\/OPTION>");
document.writeln("			<OPTION value=\"3\">求购信息<\/OPTION>");
document.writeln("			<\/SELECT>");
document.writeln("		<\/td>");
document.writeln("	<\/tr>");
document.writeln("	<tr>");
document.writeln("		<Td align=\"right\">信息类别:<\/Td>");
document.writeln("		<td>");
document.writeln("			<select name=\"xmfl\"  style=\"width:130px;height:18px;\">");
document.writeln("			<option value=\"\">类 别 不 限<\/option>");
document.writeln("			");
document.writeln("			<option value=\"A80C6HFKJ37E9B8\">商铺租售<\/option>");
document.writeln("			");
document.writeln("			<option value=\"B9B436JAJ4FC8I1\">空转门面<\/option>");
document.writeln("			");
document.writeln("			<option value=\"J6IB772HE12F33E\">厂房租售<\/option>");
document.writeln("			");
document.writeln("			<option value=\"K2A6I505C5EHGEC\">写字楼租售<\/option>");
document.writeln("			");
document.writeln("			<option value=\"85FA9JE3148CDBF\">仓库租售<\/option>");
document.writeln("			");
document.writeln("			<option value=\"DK8480F3DJ13IG8\">商住两用房<\/option>");
document.writeln("			");
document.writeln("			<option value=\"5C5C7A075CHH1CB\">独楼租售<\/option>");
document.writeln("			");
document.writeln("			<option value=\"A51HF6IJ35AB0CH\">种植园<\/option>");
document.writeln("			");
document.writeln("			<option value=\"GEGFG1K48ID3JHD\">养殖场<\/option>");
document.writeln("			");
document.writeln("			<option value=\"FAC7EH02DF71K5D\">土地租售<\/option>");
document.writeln("			");
document.writeln("			<option value=\"B71KA55K4866J52\">其它场地<\/option>");
document.writeln("			");
document.writeln("			<option value=\"2H5C531ED4BH1H0\">其它类别<\/option>");
document.writeln("			");
document.writeln("			<option value=\"DGDGFGKIDF422ID\">商标转让<\/option>");
document.writeln("			");
document.writeln("			<option value=\"I4KE96D4B3DFG91\">矿产转让<\/option>");
document.writeln("			");
document.writeln("			<option value=\"FGGE67ACGEEKHKD\">办公设备<\/option>");
document.writeln("			");
document.writeln("			<option value=\"D98KGJI114CADA3\">机械设备<\/option>");
document.writeln("			");
document.writeln("			<option value=\"DIKCE93D6HDD1DC\">汽修配件<\/option>");
document.writeln("			");
document.writeln("			<option value=\"89HDGCGH7CIBC83\">汽车美容<\/option>");
document.writeln("			");
document.writeln("			<option value=\"3477IHAA26E9KGB\">物流运输<\/option>");
document.writeln("			");
document.writeln("			<option value=\"178HDI4832E0AA5\">皮革鞋贸<\/option>");
document.writeln("			");
document.writeln("			<option value=\"6039J96147EKHKB\">服装百货<\/option>");
document.writeln("			");
document.writeln("			<option value=\"J4B759530I0KIHK\">批发零售<\/option>");
document.writeln("			");
document.writeln("			<option value=\"27KC3K0IKE84DEF\">宠物爱好<\/option>");
document.writeln("			");
document.writeln("			<option value=\"6A8DB11F83GB7HD\">鲜花礼品<\/option>");
document.writeln("			");
document.writeln("			<option value=\"16J880DGKBC9G18\">印刷影像<\/option>");
document.writeln("			");
document.writeln("			<option value=\"EDK2JG79B3HCI34\">电子通讯<\/option>");
document.writeln("			");
document.writeln("			<option value=\"IJE59K99BKK7DC9\">家具饰品<\/option>");
document.writeln("			");
document.writeln("			<option value=\"KCE5AICKKEHJKC8\">建筑装修<\/option>");
document.writeln("			");
document.writeln("			<option value=\"90E2741BD9IBAJI\">美容美发<\/option>");
document.writeln("			");
document.writeln("			<option value=\"HG54GE8471FFE3I\">网吧游戏<\/option>");
document.writeln("			");
document.writeln("			<option value=\"FC2C86II5K9ECKE\">代理加盟<\/option>");
document.writeln("			");
document.writeln("			<option value=\"A2DA91FE9785A44\">中介服务<\/option>");
document.writeln("			");
document.writeln("			<option value=\"G63DH86527C8021\">洗衣清洁<\/option>");
document.writeln("			");
document.writeln("			<option value=\"JDG298IJ4GG1K0I\">家政服务<\/option>");
document.writeln("			");
document.writeln("			<option value=\"HA924F5H7KBJ4HH\">展览展示<\/option>");
document.writeln("			");
document.writeln("			<option value=\"0DK108BI42J5H4K\">文化教育<\/option>");
document.writeln("			");
document.writeln("			<option value=\"2H5B8FA99GIH1JG\">旅游度假<\/option>");
document.writeln("			");
document.writeln("			<option value=\"996GEG79F2670BC\">酒店宾馆<\/option>");
document.writeln("			");
document.writeln("			<option value=\"8B4B1B519JKEDCB\">运动健身<\/option>");
document.writeln("			");
document.writeln("			<option value=\"112354C6AEF72J9\">股权转让<\/option>");
document.writeln("			");
document.writeln("			<option value=\"G54FDB7JF85F41C\">一般执照<\/option>");
document.writeln("			");
document.writeln("			<option value=\"760EHJ6DJ3744BI\">医药保健<\/option>");
document.writeln("			");
document.writeln("			<option value=\"56E89G8197C5H9J\">餐具消毒<\/option>");
document.writeln("			");
document.writeln("			<option value=\"5C1GEIIDB6IK0B6\">食品饮料<\/option>");
document.writeln("			");
document.writeln("			<option value=\"105HIF5C9801K0F\">酒吧歌厅<\/option>");
document.writeln("			");
document.writeln("			<option value=\"9E39K79CD1AB3KA\">桑拿按摩<\/option>");
document.writeln("			");
document.writeln("			<option value=\"H4BB394B40BC8KB\">娱乐休闲<\/option>");
document.writeln("			");
document.writeln("			<option value=\"BGDF3FE1HJF9742\">美食餐饮<\/option>");
document.writeln("			");
document.writeln("			<option value=\"9G3855D9D560GIG\">资质审批<\/option>");
document.writeln("			");
document.writeln("			<\/select>");
document.writeln("		<\/td>");
document.writeln("	<\/tr>");
document.writeln("	<tr>");
document.writeln("		<Td align=\"right\">经营面积:<\/Td>");
document.writeln("		<td>");
document.writeln("		<select name=\"mj\"  style=\"width:130px;height:18px;\">");
document.writeln("			<option  value=\"\">面 积 不 限<\/option>");
document.writeln("			<option value=\"1\" >0-100M<SUP>2<\/SUP><\/option>");
document.writeln("			<option value=\"2\" >100-200M<SUP>2<\/SUP><\/option>");
document.writeln("			<option value=\"3\" >200-500M<SUP>2<\/SUP><\/option>");
document.writeln("			<option value=\"4\" >500-1000M<SUP>2<\/SUP><\/option>");
document.writeln("			<option value=\"5\" >1000M<SUP>2<\/SUP>以上<\/option>");
document.writeln("		<\/select>");
document.writeln("		<\/td>");
document.writeln("	<\/tr>");
document.writeln("	<tr>");
document.writeln("		<Td align=\"right\">所在地区:<\/Td>");
document.writeln("		<td><select name=\"sheng\" size=\"1\" onchange=GetCapital(this.options[this.selectedIndex].value) style=\"width: 130px\">");
document.writeln("<option value=\"\" selected>选 择 地 区<\/option>");
document.writeln("<OPTION value=00>北京<\/option><OPTION value=01>天津<\/option><OPTION value=02>河北省<\/option><OPTION value=03>山西省<\/option><OPTION value=04>内蒙古<\/option><OPTION value=05>辽宁省<\/option><OPTION value=06>吉林省<\/option><OPTION value=07>黑龙江省<\/option><OPTION value=08>上海<\/option><OPTION value=09>江苏省<\/option><OPTION value=10>浙江省<\/option><OPTION value=11>安徽省<\/option><OPTION value=12>福建省<\/option><OPTION value=13>江西省<\/option><OPTION value=14>山东省<\/option><OPTION value=15>河南省<\/option><OPTION value=16>湖北省<\/option><OPTION value=17>湖南省<\/option><OPTION value=18>广东省<\/option><OPTION value=19>广西省<\/option><OPTION value=20>海南省<\/option><OPTION value=21>重庆<\/option><OPTION value=22>四川省<\/option><OPTION value=23>贵州省<\/option><OPTION value=24>云南省<\/option><OPTION value=25>西藏<\/option><OPTION value=26>陕西省<\/option><OPTION value=27>甘肃省<\/option><OPTION value=28>青海省<\/option><OPTION value=29>宁夏省<\/option><OPTION value=30>新疆<\/option><OPTION value=31>香港<\/option><OPTION value=32>澳门<\/option><OPTION value=33>台湾<\/option><\/select>");
document.writeln("<\/td>");
document.writeln("	<\/tr>");
document.writeln("	<tr>");
document.writeln("		<Td align=\"right\">所在区县:<\/Td>");
document.writeln("		<td>");
document.writeln("		<span id=\"load600\"><\/span>");
document.writeln("<span id=\"ccapital6\">");
document.writeln("<select name=\"city\" style=\"width: 130px\">");
document.writeln("<option value=\"\">所 在 区 县<\/option>");
document.writeln("<\/select><\/span> ");
document.writeln("		<\/td>");
document.writeln("	<\/tr>");
document.writeln("	<tr>");
document.writeln("		<Td align=\"right\">发布时间:<\/Td>");
document.writeln("		<td>");
document.writeln("		<select name=\"yxq\"  style=\"width:130px;height:18px;font-size:12px\">");
document.writeln("			<option  value=\"\"  selected>时 间 不 限<\/option>");
document.writeln("			<option value=3  >近三天<\/option>");
document.writeln("			<option value=7  >近一周<\/option>");
document.writeln("			<option value=14  >近二周<\/option>");
document.writeln("			<option value=30  >近一月<\/option>");
document.writeln("			<option value=60  >近二月<\/option>");
document.writeln("		<\/select>");
document.writeln("		<\/td>");
document.writeln("	<\/tr>");
document.writeln("	<Tr>");
document.writeln("		<Td align=\"right\">注册资金:<\/Td>");
document.writeln("		<td>");
document.writeln("		<select name=\"zczj\"  style=\'width:130px;height:18px;font-size:12px\'>");
document.writeln("			<option  value=\"\"  selected>资 金 不 限<\/option>");
document.writeln("			<option value=\"1\" >50万以下<\/option>");
document.writeln("			<option value=\"2\" >50-100万<\/option>");
document.writeln("			<option value=\"3\" >100-500万<\/option>");
document.writeln("			<option value=\"4\" >500万以上<\/option>");
document.writeln("		<\/select>");
document.writeln("		<\/td>");
document.writeln("	<\/Tr>");
document.writeln("	<Tr>");
document.writeln("		<Td align=\"right\">转让价格:<\/Td>");
document.writeln("		<td>");
document.writeln("		<select name=\"zsjg\" style=\'width:130px;height:18px;font-size:12px\'>");
document.writeln("			<option  value=\"\"  selected>价 格 不 限<\/option>");
document.writeln("			<option value=\"1\" >10000元以下<\/option>");
document.writeln("			<option value=\"2\" >10000元-50000元<\/option>");
document.writeln("			<option value=\"3\" >50000元-100000元<\/option>");
document.writeln("			<option value=\"4\" >100000元-1000000元<\/option>");
document.writeln("			<option value=\"5\" >1000000元-10000000元<\/option>");
document.writeln("			<option value=\"6\" >10000000元以上<\/option>");
document.writeln("		<\/select>");
document.writeln("		<\/td>");
document.writeln("	<\/Tr>");
document.writeln("	<Tr>");
document.writeln("		<Td align=\"right\">查询类别:<\/Td>");
document.writeln("		<td>");
document.writeln("			<input name=\"cxlb\" type=\"radio\" value=\"xmmc\" checked=\"checked\"\/>名称");
document.writeln("			<input type=\"radio\" name=\"cxlb\" value=\"xxbh\"\/>编号");
document.writeln("		<\/td>");
document.writeln("	<\/Tr>");
document.writeln("	<Tr>");
document.writeln("		<Td align=\"right\">关 键 字:<\/Td>");
document.writeln("		<td><input name=\"gjz\" type=\"text\" size=\"12\"><\/td>");
document.writeln("	<\/Tr>");
document.writeln("	<Tr>");
document.writeln("		<Td colspan=\"2\" align=\"center\"><input type=\"submit\" name=\"Submit\" value=\"我 要 搜 索\" onclick=\"return checksjiansuo();\"><\/Td>");
document.writeln("	<\/Tr>");
document.writeln("<\/form>");
document.writeln("<\/Table>");